### ISSUE TITLE
Question about the EMC module

### ISSUE THREAD

**Issue by solub** [backtracking/combine#7]
Hi,

I would like to know if the EMC module use the ZDD to accelerate the depth-first-search of DLX (as in the [DXZ](https://aaai.org/ocs/index.php/AAAI/AAAI17/paper/view/14907/13855) algorithm), or if it makes use of the 2 separately.

**Comment by backtracking** [comment]
Hi,

It makes use of the two separately.

And thanks for pointing out this paper!

-- 
Jean-Christophe

**Comment by solub** [comment]
Thanks for the quick reply. You're welcome!

Although I don't have any experience with OCaml (yet) and just heard about "Combine", I believe this could be a great addition to the library. For the tiling of polyominoes the authors are mentioning a speed-up by several orders of magnitude (!)

**Comment by backtracking** [comment]
You're right, it would be a nice addition. (I quickly went through the
paper and it indeed looks promising.)
